//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotecaEntitiesORM : DbContext
    {
        public BibliotecaEntitiesORM()
            : base("name=BibliotecaEntitiesORM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autore> Autores { get; set; }
        public virtual DbSet<EstadosLectura> EstadosLecturas { get; set; }
        public virtual DbSet<Libro> Libros { get; set; }
        public virtual DbSet<Genero> Generos { get; set; }
    }
}
