//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public Nullable<int> IdAutor { get; set; }
        public Nullable<int> IdEstadoLectura { get; set; }
        public Nullable<int> Publicacion { get; set; }
    
        public virtual Autore Autore { get; set; }
        public virtual EstadosLectura EstadosLectura { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
